#ifndef DBW_NODE_PINS_H
#define DBW_NODE_PINS_H

/* LEDs */
#define NODE_BOARD_PIN_LED1 32
#define NODE_BOARD_PIN_LED2 33

/* CAN */
#define NODE_BOARD_PIN_CANTX 19
#define NODE_BOARD_PIN_CANRX 18

/* EEPROM */
#define NODE_BOARD_PIN_EEPROM_WP  21
#define NODE_BOARD_PIN_EEPROM_SDA 22
#define NODE_BOARD_PIN_EEPROM_SCL 23

#endif
