#ifndef DBW_NODE_PINS_H
#define DBW_NODE_PINS_H

/* LEDs */
#define NODE_BOARD_PIN_LED1 46
#define NODE_BOARD_PIN_LED2 45

/* CAN */
#define NODE_BOARD_PIN_CANTX 39
#define NODE_BOARD_PIN_CANRX 38

/* EEPROM */
#define NODE_BOARD_PIN_EEPROM_WP  42
#define NODE_BOARD_PIN_EEPROM_SDA 26
#define NODE_BOARD_PIN_EEPROM_SCL 21

#endif
